-- Phase 14: platform operations.  Everything here is internal runtime state and global aggregate
-- observation.  No tenant row, customer identifier, message body, or provider identifier is stored
-- or returned, and nothing in this migration mutates product state.

-- The deployed schema advertises a compatibility version so a release can refuse to serve traffic
-- against a database that has not been migrated yet.  It is a singleton by construction.
create table public.platform_schema_contract (
  id boolean primary key default true check (id),
  schema_version integer not null check (schema_version between 1 and 100000),
  updated_at timestamptz not null default now()
);
insert into public.platform_schema_contract (id, schema_version) values (true, 14);

-- One row per API process.  The identifier is ephemeral and generated by the process itself; it is
-- never an authorization subject, and host or container identity is deliberately not recorded.
create table public.runtime_instances (
  instance_id uuid primary key,
  service text not null check (char_length(service) between 1 and 60),
  release text not null default 'unknown' check (char_length(release) between 1 and 120),
  started_at timestamptz not null default now(),
  last_heartbeat_at timestamptz not null default now(),
  stopped_at timestamptz
);
create index runtime_instances_active_idx
  on public.runtime_instances (last_heartbeat_at desc)
  where stopped_at is null;

-- One row per component per process.  "No work" is a successful tick, so last_success_at moves on
-- an empty poll and only a real failure increments the failure counter.
create table public.runtime_component_heartbeats (
  id uuid primary key default extensions.gen_random_uuid(),
  instance_id uuid not null references public.runtime_instances (instance_id) on delete cascade,
  component text not null check (component in (
    'message_processing', 'appointment_reminders', 'lead_followups', 'billing_events'
  )),
  state text not null check (state in ('starting', 'running', 'stopping', 'stopped')),
  last_tick_at timestamptz,
  last_success_at timestamptz,
  consecutive_failures integer not null default 0 check (consecutive_failures between 0 and 1000000),
  last_error_code text check (last_error_code is null or char_length(last_error_code) between 1 and 60),
  updated_at timestamptz not null default now(),
  constraint runtime_component_heartbeats_instance_component_key unique (instance_id, component)
);
create index runtime_component_heartbeats_component_idx
  on public.runtime_component_heartbeats (component, updated_at desc);

alter table public.platform_schema_contract enable row level security;
alter table public.runtime_instances enable row level security;
alter table public.runtime_component_heartbeats enable row level security;

-- Platform operational state is not tenant data and has no tenant reader.  There is deliberately no
-- select policy: every read goes through a narrow service-role function.
revoke all on table public.platform_schema_contract, public.runtime_instances,
  public.runtime_component_heartbeats
  from public, anon, authenticated, service_role;

-- Operational aggregation reads durable queue state by status.  These predicates are narrow and
-- match the states an operator can act on; nothing indexes message or customer text.
create index message_deliveries_unresolved_idx
  on public.message_deliveries (status, updated_at)
  where status in ('queued', 'submitting', 'unknown', 'failed', 'undelivered');
create index booking_intents_ambiguous_idx
  on public.booking_intents (updated_at)
  where status = 'provider_state_unknown';
create index appointment_change_intents_ambiguous_idx
  on public.appointment_change_intents (updated_at)
  where status in ('provider_state_unknown', 'provider_success_pending_persistence', 'handoff_required');

create function public.require_platform_service_role()
returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.role() <> 'service_role' then
    raise exception using errcode = '42501', message = 'Trusted platform operations access is required';
  end if;
end;
$$;

-- The readiness probe is deliberately the cheapest useful query: it proves the database answers and
-- reports the compatibility version, and returns nothing else.
create function public.platform_readiness_probe()
returns table (checked_at timestamptz, schema_version integer)
language plpgsql stable security definer set search_path = '' as $$
begin
  perform public.require_platform_service_role();
  return query
  select now(), contract.schema_version from public.platform_schema_contract contract where contract.id;
end;
$$;

-- Runtime history is bounded.  Stopped processes are kept for a short operational window so a
-- recent restart is still explainable, and instances that stopped reporting long ago are removed.
-- Rows that are merely stale are kept, because a silently dead process is itself a diagnosis.
create function public.prune_runtime_instances()
returns integer language plpgsql security definer set search_path = '' as $$
declare removed integer;
begin
  with deleted as (
    delete from public.runtime_instances instance
    where (instance.stopped_at is not null and instance.stopped_at < now() - interval '2 days')
       or instance.last_heartbeat_at < now() - interval '7 days'
    returning 1
  )
  select count(*)::integer into removed from deleted;
  return removed;
end;
$$;

create function public.register_runtime_instance(
  target_instance_id uuid,
  target_service text,
  target_release text
)
returns void language plpgsql security definer set search_path = '' as $$
begin
  perform public.require_platform_service_role();
  if target_instance_id is null
    or char_length(btrim(coalesce(target_service, ''))) not between 1 and 60
    or char_length(btrim(coalesce(target_release, ''))) not between 1 and 120 then
    raise exception using errcode = '22023', message = 'Runtime instance registration is invalid';
  end if;
  insert into public.runtime_instances (instance_id, service, release)
  values (target_instance_id, btrim(target_service), btrim(target_release))
  on conflict (instance_id) do update
    set last_heartbeat_at = now(), stopped_at = null;
  perform public.prune_runtime_instances();
end;
$$;

-- A component tick is one bounded write.  Success clears the failure streak; failure increments it
-- and keeps a short error code only, never a stack trace or provider payload.
create function public.heartbeat_runtime_component(
  target_instance_id uuid,
  target_component text,
  target_state text,
  target_succeeded boolean,
  target_error_code text default null
)
returns void language plpgsql security definer set search_path = '' as $$
declare normalized_error text := left(nullif(btrim(coalesce(target_error_code, '')), ''), 60);
begin
  perform public.require_platform_service_role();
  if target_state not in ('starting', 'running', 'stopping', 'stopped') then
    raise exception using errcode = '22023', message = 'Runtime component state is invalid';
  end if;
  if not exists (
    select 1 from public.runtime_instances instance where instance.instance_id = target_instance_id
  ) then
    raise exception using errcode = '42501', message = 'Runtime instance is not registered';
  end if;

  update public.runtime_instances set last_heartbeat_at = now()
  where instance_id = target_instance_id;

  insert into public.runtime_component_heartbeats (
    instance_id, component, state, last_tick_at, last_success_at, consecutive_failures, last_error_code
  ) values (
    target_instance_id, target_component, target_state,
    case when target_succeeded is null then null else now() end,
    case when target_succeeded then now() else null end,
    case when target_succeeded is not distinct from false then 1 else 0 end,
    case when target_succeeded is not distinct from false then normalized_error else null end
  )
  on conflict on constraint runtime_component_heartbeats_instance_component_key do update set
    state = excluded.state,
    last_tick_at = case
      when target_succeeded is null then public.runtime_component_heartbeats.last_tick_at
      else now() end,
    last_success_at = case
      when target_succeeded then now()
      else public.runtime_component_heartbeats.last_success_at end,
    consecutive_failures = case
      when target_succeeded then 0
      when target_succeeded is null then public.runtime_component_heartbeats.consecutive_failures
      else public.runtime_component_heartbeats.consecutive_failures + 1 end,
    last_error_code = case
      when target_succeeded then null
      when target_succeeded is null then public.runtime_component_heartbeats.last_error_code
      else normalized_error end,
    updated_at = now();
end;
$$;

-- Stopping one process must never mark another one stopped.
create function public.stop_runtime_instance(target_instance_id uuid)
returns void language plpgsql security definer set search_path = '' as $$
begin
  perform public.require_platform_service_role();
  update public.runtime_instances
  set stopped_at = now(), last_heartbeat_at = now()
  where instance_id = target_instance_id and stopped_at is null;
  update public.runtime_component_heartbeats
  set state = 'stopped', updated_at = now()
  where instance_id = target_instance_id and state <> 'stopped';
end;
$$;

-- Runtime status for the trusted operator CLI: which processes are reporting, on which release,
-- and how fresh each component tick is.  Multi-replica by construction.
create function public.get_platform_runtime_status()
returns table (
  instance_id uuid,
  service text,
  release text,
  started_at timestamptz,
  last_heartbeat_at timestamptz,
  stopped_at timestamptz,
  component text,
  component_state text,
  last_tick_at timestamptz,
  last_success_at timestamptz,
  consecutive_failures integer,
  last_error_code text
)
language plpgsql stable security definer set search_path = '' as $$
begin
  perform public.require_platform_service_role();
  return query
  select
    instance.instance_id, instance.service, instance.release, instance.started_at,
    instance.last_heartbeat_at, instance.stopped_at,
    heartbeat.component, heartbeat.state, heartbeat.last_tick_at, heartbeat.last_success_at,
    heartbeat.consecutive_failures, heartbeat.last_error_code
  from public.runtime_instances instance
  left join public.runtime_component_heartbeats heartbeat
    on heartbeat.instance_id = instance.instance_id
  order by instance.started_at desc, heartbeat.component asc;
end;
$$;

-- One global aggregate snapshot in a long format so a future exporter can consume it without a
-- schema change.  Values are counts; oldest_at is the age of the oldest item in that state; detail
-- is a bounded operational label.  There is no tenant identifier, contact, body, or provider ID.
create function public.get_platform_operational_snapshot()
returns table (metric_group text, metric text, value bigint, oldest_at timestamptz, detail text)
language plpgsql stable security definer set search_path = '' as $$
begin
  perform public.require_platform_service_role();

  return query
  -- Runtime: an instance counts as active only while it has not stopped and is still reporting.
  select 'runtime'::text, 'active_instances'::text,
    count(*) filter (where instance.stopped_at is null)::bigint,
    min(instance.started_at) filter (where instance.stopped_at is null),
    null::text
  from public.runtime_instances instance
  union all
  select 'runtime'::text, 'release'::text, count(*)::bigint, min(instance.started_at), instance.release
  from public.runtime_instances instance
  where instance.stopped_at is null
  group by instance.release
  union all
  select 'runtime_component'::text, heartbeat.component, count(*)::bigint,
    min(heartbeat.last_success_at), heartbeat.state
  from public.runtime_component_heartbeats heartbeat
  join public.runtime_instances instance on instance.instance_id = heartbeat.instance_id
  where instance.stopped_at is null
  group by heartbeat.component, heartbeat.state

  -- Message processing jobs.
  union all
  select 'message_jobs'::text, job.status, count(*)::bigint, min(job.created_at), null::text
  from public.message_processing_jobs job
  where job.status in ('queued', 'processing', 'failed')
  group by job.status
  union all
  select 'message_jobs'::text, 'expired_lease'::text, count(*)::bigint, min(job.claimed_at), null::text
  from public.message_processing_jobs job
  where job.status = 'processing' and job.claimed_at < now() - interval '5 minutes'

  -- Durable SMS delivery truth.  Nothing here changes a provider status.
  union all
  select 'sms_delivery'::text, delivery.status, count(*)::bigint, min(delivery.updated_at), null::text
  from public.message_deliveries delivery
  where delivery.status in ('queued', 'submitting', 'unknown', 'failed', 'undelivered')
  group by delivery.status

  -- Reminders.  Work scheduled for the future is reported separately and is never backlog.
  union all
  select 'reminders'::text, 'due'::text, count(*)::bigint, min(reminder.scheduled_for), null::text
  from public.appointment_reminders reminder
  where reminder.status = 'scheduled' and reminder.scheduled_for <= now()
  union all
  select 'reminders'::text, 'scheduled_future'::text, count(*)::bigint, min(reminder.scheduled_for), null::text
  from public.appointment_reminders reminder
  where reminder.status = 'scheduled' and reminder.scheduled_for > now()
  union all
  select 'reminders'::text, reminder.status, count(*)::bigint, min(reminder.updated_at), null::text
  from public.appointment_reminders reminder
  where reminder.status in ('processing', 'delivery_pending', 'failed')
  group by reminder.status

  -- Lead follow-ups.  Suppressed work is visible but is never reopened by reading it.
  union all
  select 'lead_followups'::text, 'due'::text, count(*)::bigint, min(job.scheduled_for), null::text
  from public.lead_followup_jobs job
  where job.status = 'scheduled' and job.scheduled_for <= now()
  union all
  select 'lead_followups'::text, 'scheduled_future'::text, count(*)::bigint, min(job.scheduled_for), null::text
  from public.lead_followup_jobs job
  where job.status = 'scheduled' and job.scheduled_for > now()
  union all
  select 'lead_followups'::text, job.status, count(*)::bigint, min(job.updated_at), null::text
  from public.lead_followup_jobs job
  where job.status in ('processing', 'delivery_pending', 'failed', 'skipped')
  group by job.status

  -- Stripe webhook worker.  No Stripe identifier is exposed.
  union all
  select 'billing_events'::text, event.status, count(*)::bigint, min(event.received_at), null::text
  from public.stripe_webhook_events event
  where event.status in ('pending', 'processing', 'failed')
  group by event.status

  -- Ambiguous provider write truth.  Reading it never reconciles or invents a provider outcome.
  union all
  select 'booking_intents'::text, 'provider_state_unknown'::text, count(*)::bigint,
    min(intent.updated_at), null::text
  from public.booking_intents intent
  where intent.status = 'provider_state_unknown'
  union all
  select 'appointment_change_intents'::text, intent.status, count(*)::bigint,
    min(intent.updated_at), null::text
  from public.appointment_change_intents intent
  where intent.status in ('provider_state_unknown', 'provider_success_pending_persistence', 'handoff_required')
  group by intent.status;
end;
$$;

-- Internal helpers are not a callable boundary.  The trusted backend gets exactly the narrow
-- registration, heartbeat, stop, probe, and read functions it needs, and nothing else.
revoke all on function
  public.require_platform_service_role(),
  public.prune_runtime_instances(),
  public.platform_readiness_probe(),
  public.register_runtime_instance(uuid, text, text),
  public.heartbeat_runtime_component(uuid, text, text, boolean, text),
  public.stop_runtime_instance(uuid),
  public.get_platform_runtime_status(),
  public.get_platform_operational_snapshot()
  from public, anon, authenticated, service_role;

grant execute on function
  public.platform_readiness_probe(),
  public.register_runtime_instance(uuid, text, text),
  public.heartbeat_runtime_component(uuid, text, text, boolean, text),
  public.stop_runtime_instance(uuid),
  public.get_platform_runtime_status(),
  public.get_platform_operational_snapshot()
  to service_role;
